# Generated by Django 4.0.6 on 2023-04-16 10:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_dietplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='dietplan',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
